CREATE TABLE categoria (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nome VARCHAR(100) NOT NULL,
                           descricao VARCHAR(255),
                           ordem INT NOT NULL DEFAULT 0,
                           status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
                           created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);