-- =====================================================================
-- V2: cria as demais tabelas do sistema (a tabela categoria veio na V1)
-- Segue a secao 06 do SRS. Colunas marcadas com "extra" nao estao na
-- lista do professor, mas sao necessarias para algum requisito (RF).
-- =====================================================================

-- ---------- Usuarios (clientes e equipe interna) ----------
CREATE TABLE usuario (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(120) NOT NULL,
    email       VARCHAR(160) NOT NULL,
    senha_hash  VARCHAR(100) NOT NULL,
    perfil      VARCHAR(20)  NOT NULL,
    telefone    VARCHAR(20),
    endereco    VARCHAR(255),
    status      VARCHAR(20)  NOT NULL DEFAULT 'ATIVO',
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_usuario_email  UNIQUE (email),
    CONSTRAINT ck_usuario_perfil CHECK (perfil IN ('ADMIN', 'GERENTE', 'COZINHEIRO', 'CLIENTE')),
    CONSTRAINT ck_usuario_status CHECK (status IN ('ATIVO', 'INATIVO'))
);

-- ---------- Cardapio ----------
CREATE TABLE prato (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id      BIGINT        NOT NULL,
    nome              VARCHAR(120)  NOT NULL,
    descricao         VARCHAR(500),
    foto_url          VARCHAR(500),
    preco_venda       NUMERIC(10,2) NOT NULL,
    tempo_preparo_min INT           NOT NULL DEFAULT 15,
    anime             VARCHAR(80),  -- extra: tema do Gojo Purin
    personagem        VARCHAR(80),  -- extra: tema do Gojo Purin
    status            VARCHAR(20)   NOT NULL DEFAULT 'INATIVO',
    created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prato_categoria FOREIGN KEY (categoria_id) REFERENCES categoria (id),
    CONSTRAINT ck_prato_status    CHECK (status IN ('ATIVO', 'INATIVO', 'PAUSADO')),
    CONSTRAINT ck_prato_preco     CHECK (preco_venda >= 0)
);

-- ---------- Estoque: ingredientes ----------
CREATE TABLE ingrediente (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(120)  NOT NULL,
    sku            VARCHAR(30)   NOT NULL,
    unidade_padrao VARCHAR(5)    NOT NULL,
    estoque_minimo NUMERIC(12,3) NOT NULL DEFAULT 0,
    custo_unitario NUMERIC(10,4) NOT NULL DEFAULT 0,
    status         VARCHAR(20)   NOT NULL DEFAULT 'ATIVO',
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ingrediente_sku     UNIQUE (sku),
    CONSTRAINT ck_ingrediente_unidade CHECK (unidade_padrao IN ('G', 'ML', 'UN', 'KG', 'L')),
    CONSTRAINT ck_ingrediente_status  CHECK (status IN ('ATIVO', 'INATIVO'))
);

-- ---------- Ficha tecnica (1 por prato) ----------
CREATE TABLE ficha_tecnica (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prato_id     BIGINT    NOT NULL,
    rendimento   INT       NOT NULL DEFAULT 1,
    modo_preparo TEXT,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ficha_tecnica_prato UNIQUE (prato_id),
    CONSTRAINT fk_ficha_tecnica_prato FOREIGN KEY (prato_id) REFERENCES prato (id),
    CONSTRAINT ck_ficha_rendimento    CHECK (rendimento >= 1)
);

CREATE TABLE ficha_tecnica_item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ficha_tecnica_id BIGINT        NOT NULL,
    ingrediente_id   BIGINT        NOT NULL,
    quantidade       NUMERIC(12,3) NOT NULL,
    unidade          VARCHAR(5)    NOT NULL,
    fator_correcao   NUMERIC(5,2)  NOT NULL DEFAULT 1.00,
    CONSTRAINT fk_fti_ficha       FOREIGN KEY (ficha_tecnica_id) REFERENCES ficha_tecnica (id),
    CONSTRAINT fk_fti_ingrediente FOREIGN KEY (ingrediente_id)   REFERENCES ingrediente (id),
    CONSTRAINT uk_fti_ficha_ingrediente UNIQUE (ficha_tecnica_id, ingrediente_id),
    CONSTRAINT ck_fti_quantidade  CHECK (quantidade > 0),
    CONSTRAINT ck_fti_fator       CHECK (fator_correcao >= 1.00)
);

-- ---------- Fornecedores ----------
CREATE TABLE fornecedor (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social        VARCHAR(160) NOT NULL,
    cnpj                VARCHAR(14)  NOT NULL,  -- somente os 14 digitos
    telefone            VARCHAR(20),
    email               VARCHAR(160),
    categorias_produtos VARCHAR(255),           -- extra: pedido no RF-021
    status              VARCHAR(20)  NOT NULL DEFAULT 'ATIVO',
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_fornecedor_cnpj   UNIQUE (cnpj),
    CONSTRAINT ck_fornecedor_status CHECK (status IN ('ATIVO', 'INATIVO'))
);

-- Catalogo: "esse fornecedor vende esse ingrediente por esse preco"
CREATE TABLE fornecedor_produto (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id  BIGINT        NOT NULL,
    ingrediente_id BIGINT        NOT NULL,
    preco          NUMERIC(10,4) NOT NULL,
    unidade_venda  VARCHAR(5)    NOT NULL,
    CONSTRAINT fk_fp_fornecedor  FOREIGN KEY (fornecedor_id)  REFERENCES fornecedor (id),
    CONSTRAINT fk_fp_ingrediente FOREIGN KEY (ingrediente_id) REFERENCES ingrediente (id),
    CONSTRAINT uk_fp_fornecedor_ingrediente UNIQUE (fornecedor_id, ingrediente_id)
);

-- extra: historico de precos para o grafico do RF-026
CREATE TABLE fornecedor_preco_historico (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id  BIGINT        NOT NULL,
    ingrediente_id BIGINT        NOT NULL,
    preco          NUMERIC(10,4) NOT NULL,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fph_fornecedor  FOREIGN KEY (fornecedor_id)  REFERENCES fornecedor (id),
    CONSTRAINT fk_fph_ingrediente FOREIGN KEY (ingrediente_id) REFERENCES ingrediente (id)
);

-- ---------- Compras ----------
CREATE TABLE pedido_compra (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id BIGINT        NOT NULL,
    status        VARCHAR(20)   NOT NULL DEFAULT 'RASCUNHO',
    valor_total   NUMERIC(12,2) NOT NULL DEFAULT 0,
    usuario_id    BIGINT        NOT NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pc_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES fornecedor (id),
    CONSTRAINT fk_pc_usuario    FOREIGN KEY (usuario_id)    REFERENCES usuario (id),
    CONSTRAINT ck_pc_status     CHECK (status IN ('RASCUNHO', 'ENVIADO', 'RECEBIDO', 'CANCELADO'))
);

CREATE TABLE pedido_compra_item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_compra_id BIGINT        NOT NULL,
    ingrediente_id   BIGINT        NOT NULL,
    quantidade       NUMERIC(12,3) NOT NULL,
    preco_unitario   NUMERIC(10,4) NOT NULL,
    subtotal         NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_pci_pedido_compra FOREIGN KEY (pedido_compra_id) REFERENCES pedido_compra (id),
    CONSTRAINT fk_pci_ingrediente   FOREIGN KEY (ingrediente_id)   REFERENCES ingrediente (id),
    CONSTRAINT ck_pci_quantidade    CHECK (quantidade > 0)
);

-- ---------- Pedidos dos clientes ----------
CREATE TABLE pedido (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id          BIGINT        NOT NULL,
    status              VARCHAR(20)   NOT NULL DEFAULT 'RECEBIDO',
    valor_total         NUMERIC(12,2) NOT NULL,
    endereco_entrega    VARCHAR(255)  NOT NULL,
    observacoes         VARCHAR(500),
    motivo_cancelamento VARCHAR(255),
    canal               VARCHAR(20)   NOT NULL DEFAULT 'SITE',  -- extra: filtro do RF-019
    pago                BOOLEAN       NOT NULL DEFAULT FALSE,   -- extra: pagamento simulado do RF-006
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES usuario (id),
    CONSTRAINT ck_pedido_status  CHECK (status IN ('RECEBIDO', 'CONFIRMADO', 'EM_PREPARO', 'PRONTO',
                                                   'SAIU_ENTREGA', 'FINALIZADO', 'CANCELADO'))
);

CREATE TABLE pedido_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      BIGINT        NOT NULL,
    prato_id       BIGINT        NOT NULL,
    quantidade     INT           NOT NULL,
    preco_unitario NUMERIC(10,2) NOT NULL,
    observacoes    VARCHAR(255),
    CONSTRAINT fk_pi_pedido  FOREIGN KEY (pedido_id) REFERENCES pedido (id),
    CONSTRAINT fk_pi_prato   FOREIGN KEY (prato_id)  REFERENCES prato (id),
    CONSTRAINT ck_pi_quantidade CHECK (quantidade > 0)
);

-- extra: cada troca de status vira uma linha (timeline do RF-007 e RF-020)
CREATE TABLE pedido_status_historico (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id  BIGINT      NOT NULL,
    status     VARCHAR(20) NOT NULL,
    usuario_id BIGINT,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_psh_pedido  FOREIGN KEY (pedido_id)  REFERENCES pedido (id),
    CONSTRAINT fk_psh_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

-- ---------- Movimentacoes de estoque ----------
-- O saldo de um ingrediente e a soma das ENTRADAS e ESTORNOS menos as SAIDAS.
CREATE TABLE estoque_movimentacao (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingrediente_id   BIGINT        NOT NULL,
    tipo             VARCHAR(20)   NOT NULL,
    quantidade       NUMERIC(12,3) NOT NULL,
    motivo           VARCHAR(20)   NOT NULL,
    lote             VARCHAR(50),
    validade         DATE,
    custo_unitario   NUMERIC(10,4),
    pedido_compra_id BIGINT,
    pedido_id        BIGINT,
    usuario_id       BIGINT        NOT NULL,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_em_ingrediente   FOREIGN KEY (ingrediente_id)   REFERENCES ingrediente (id),
    CONSTRAINT fk_em_pedido_compra FOREIGN KEY (pedido_compra_id) REFERENCES pedido_compra (id),
    CONSTRAINT fk_em_pedido        FOREIGN KEY (pedido_id)        REFERENCES pedido (id),
    CONSTRAINT fk_em_usuario       FOREIGN KEY (usuario_id)       REFERENCES usuario (id),
    CONSTRAINT ck_em_tipo       CHECK (tipo IN ('ENTRADA', 'SAIDA', 'ESTORNO')),
    CONSTRAINT ck_em_motivo     CHECK (motivo IN ('COMPRA', 'VENDA', 'DESPERDICIO', 'VENCIMENTO',
                                                  'QUEBRA', 'USO_INTERNO', 'AJUSTE', 'ESTORNO')),
    CONSTRAINT ck_em_quantidade CHECK (quantidade > 0)
);

-- ---------- Indices para as consultas mais comuns ----------
CREATE INDEX idx_prato_categoria        ON prato (categoria_id);
CREATE INDEX idx_prato_status           ON prato (status);
CREATE INDEX idx_fti_ingrediente        ON ficha_tecnica_item (ingrediente_id);
CREATE INDEX idx_fp_ingrediente         ON fornecedor_produto (ingrediente_id);
CREATE INDEX idx_fph_ingrediente        ON fornecedor_preco_historico (ingrediente_id, fornecedor_id);
CREATE INDEX idx_pci_pedido_compra      ON pedido_compra_item (pedido_compra_id);
CREATE INDEX idx_pedido_cliente         ON pedido (cliente_id);
CREATE INDEX idx_pedido_status_data     ON pedido (status, created_at);
CREATE INDEX idx_pi_pedido              ON pedido_item (pedido_id);
CREATE INDEX idx_psh_pedido             ON pedido_status_historico (pedido_id);
CREATE INDEX idx_em_ingrediente         ON estoque_movimentacao (ingrediente_id);
CREATE INDEX idx_em_pedido              ON estoque_movimentacao (pedido_id);
