-- =====================================================================
-- V4: complementos dos pratos e combos
-- Nao fazem parte do SRS: sao o diferencial do Gojo Purin.
-- =====================================================================

-- ---------- Complementos ----------
-- Um grupo e uma pergunta feita ao cliente ("Ponto do ovo", "Adicionais").
-- min_escolhas e max_escolhas dizem quantas opcoes ele pode marcar.
CREATE TABLE grupo_opcao (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR(100) NOT NULL,
    obrigatorio  BOOLEAN      NOT NULL DEFAULT FALSE,
    min_escolhas INT          NOT NULL DEFAULT 0,
    max_escolhas INT          NOT NULL DEFAULT 1,
    status       VARCHAR(20)  NOT NULL DEFAULT 'ATIVO',
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_grupo_opcao_nome UNIQUE (nome),
    CONSTRAINT ck_grupo_opcao_status   CHECK (status IN ('ATIVO', 'INATIVO')),
    CONSTRAINT ck_grupo_opcao_escolhas CHECK (min_escolhas >= 0 AND max_escolhas >= 1 AND max_escolhas >= min_escolhas)
);

-- Cada resposta possivel de um grupo. Um adicional pago pode consumir estoque:
-- ingrediente_id e quantidade_ingrediente dizem o que baixar (ex.: 1 ovo).
CREATE TABLE opcao (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_opcao_id         BIGINT        NOT NULL,
    nome                   VARCHAR(100)  NOT NULL,
    preco_adicional        NUMERIC(10,2) NOT NULL DEFAULT 0,
    ingrediente_id         BIGINT,
    quantidade_ingrediente NUMERIC(12,3),
    ordem                  INT           NOT NULL DEFAULT 0,
    status                 VARCHAR(20)   NOT NULL DEFAULT 'ATIVO',
    CONSTRAINT fk_opcao_grupo       FOREIGN KEY (grupo_opcao_id) REFERENCES grupo_opcao (id),
    CONSTRAINT fk_opcao_ingrediente FOREIGN KEY (ingrediente_id) REFERENCES ingrediente (id),
    CONSTRAINT ck_opcao_status CHECK (status IN ('ATIVO', 'INATIVO')),
    CONSTRAINT ck_opcao_preco  CHECK (preco_adicional >= 0)
);

-- Liga cada prato aos grupos que ele oferece. O mesmo grupo serve a varios pratos.
CREATE TABLE prato_grupo_opcao (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prato_id       BIGINT NOT NULL,
    grupo_opcao_id BIGINT NOT NULL,
    ordem          INT    NOT NULL DEFAULT 0,
    CONSTRAINT fk_pgo_prato FOREIGN KEY (prato_id)       REFERENCES prato (id),
    CONSTRAINT fk_pgo_grupo FOREIGN KEY (grupo_opcao_id) REFERENCES grupo_opcao (id),
    CONSTRAINT uk_pgo_prato_grupo UNIQUE (prato_id, grupo_opcao_id)
);

-- ---------- Combos ----------
-- PRONTO: os pratos ja vem escolhidos. MONTAVEL: o cliente escolhe em cada etapa.
-- O preco do combo e a soma dos pratos menos o desconto_percentual.
CREATE TABLE combo (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR(120) NOT NULL,
    descricao           VARCHAR(500),
    tipo                VARCHAR(20)  NOT NULL,
    desconto_percentual NUMERIC(5,2) NOT NULL DEFAULT 0,
    foto_url            VARCHAR(500),
    ordem               INT          NOT NULL DEFAULT 0,
    status              VARCHAR(20)  NOT NULL DEFAULT 'ATIVO',
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_combo_tipo     CHECK (tipo IN ('PRONTO', 'MONTAVEL')),
    CONSTRAINT ck_combo_status   CHECK (status IN ('ATIVO', 'INATIVO')),
    CONSTRAINT ck_combo_desconto CHECK (desconto_percentual >= 0 AND desconto_percentual <= 90)
);

-- Cada etapa e uma escolha dentro do combo ("Prato", "Bebida", "Sobremesa").
CREATE TABLE combo_etapa (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    combo_id    BIGINT       NOT NULL,
    nome        VARCHAR(100) NOT NULL,
    obrigatoria BOOLEAN      NOT NULL DEFAULT TRUE,
    ordem       INT          NOT NULL DEFAULT 0,
    CONSTRAINT fk_combo_etapa_combo FOREIGN KEY (combo_id) REFERENCES combo (id)
);

-- Os pratos que podem ser escolhidos em cada etapa.
CREATE TABLE combo_etapa_prato (
    combo_etapa_id BIGINT NOT NULL,
    prato_id       BIGINT NOT NULL,
    PRIMARY KEY (combo_etapa_id, prato_id),
    CONSTRAINT fk_cep_etapa FOREIGN KEY (combo_etapa_id) REFERENCES combo_etapa (id),
    CONSTRAINT fk_cep_prato FOREIGN KEY (prato_id)       REFERENCES prato (id)
);

CREATE INDEX idx_opcao_grupo       ON opcao (grupo_opcao_id);
CREATE INDEX idx_pgo_prato         ON prato_grupo_opcao (prato_id);
CREATE INDEX idx_combo_etapa_combo ON combo_etapa (combo_id);

-- =====================================================================
-- Dados iniciais
-- =====================================================================

INSERT INTO grupo_opcao (nome, obrigatorio, min_escolhas, max_escolhas) VALUES
('Ponto do ovo',        TRUE,  1, 1),
('Nível de pimenta',    TRUE,  1, 1),
('Gelo',                TRUE,  1, 1),
('Adicionais do ramen', FALSE, 0, 3),
('Adicionais',          FALSE, 0, 2),
('Molho extra',         FALSE, 0, 2),
('Cobertura extra',     FALSE, 0, 2),
('Adicionais da massa', FALSE, 0, 2);

INSERT INTO opcao (grupo_opcao_id, nome, preco_adicional, ingrediente_id, quantidade_ingrediente, ordem)
SELECT g.id, v.nome, v.preco, i.id, v.quantidade, v.ordem
FROM (VALUES
 ('Ponto do ovo',        'Gema mole',                  0.00, NULL,      NULL, 1),
 ('Ponto do ovo',        'Ao ponto',                   0.00, NULL,      NULL, 2),
 ('Ponto do ovo',        'Bem cozido',                 0.00, NULL,      NULL, 3),
 ('Nível de pimenta',    'Sem pimenta',                0.00, NULL,      NULL, 1),
 ('Nível de pimenta',    'Suave',                      0.00, NULL,      NULL, 2),
 ('Nível de pimenta',    'Picante',                    0.00, NULL,      NULL, 3),
 ('Gelo',                'Com gelo',                   0.00, NULL,      NULL, 1),
 ('Gelo',                'Pouco gelo',                 0.00, NULL,      NULL, 2),
 ('Gelo',                'Sem gelo',                   0.00, NULL,      NULL, 3),
 ('Adicionais do ramen', 'Ovo extra',                  4.00, 'ING-004',    1, 1),
 ('Adicionais do ramen', 'Chashu extra',               8.00, 'ING-003',   60, 2),
 ('Adicionais do ramen', 'Macarrão extra',             5.00, 'ING-001',   80, 3),
 ('Adicionais',          'Ovo extra',                  4.00, 'ING-004',    1, 1),
 ('Adicionais',          'Arroz extra',                5.00, 'ING-007',  100, 2),
 ('Molho extra',         'Maionese japonesa',          2.00, 'ING-023',   20, 1),
 ('Molho extra',         'Molho agridoce',             2.00, 'ING-034',   30, 2),
 ('Molho extra',         'Molho picante da casa',      2.00, 'ING-032',   30, 3),
 ('Cobertura extra',     'Calda de frutas vermelhas',  3.00, 'ING-040',   30, 1),
 ('Cobertura extra',     'Creme batido',               3.00, 'ING-042',   30, 2),
 ('Cobertura extra',     'Raspas de chocolate',        3.00, 'ING-045',   15, 3),
 ('Adicionais da massa', 'Parmesão extra',             4.00, 'ING-055',   15, 1),
 ('Adicionais da massa', 'Shimeji extra',              6.00, 'ING-054',   40, 2)
) AS v (grupo, nome, preco, sku, quantidade, ordem)
JOIN grupo_opcao g      ON g.nome = v.grupo
LEFT JOIN ingrediente i ON i.sku = v.sku;

-- Quais grupos cada prato oferece (o numero e a ordem em que aparecem na tela).
INSERT INTO prato_grupo_opcao (prato_id, grupo_opcao_id, ordem)
SELECT p.id, g.id, v.ordem
FROM (VALUES
 ('Ramen Ichiraku',         'Ponto do ovo', 1),        ('Ramen Ichiraku',         'Adicionais do ramen', 2),
 ('Black Garlic Ramen',     'Ponto do ovo', 1),        ('Black Garlic Ramen',     'Adicionais do ramen', 2),
 ('Curry do Sanji',         'Nível de pimenta', 1),    ('Curry do Sanji',         'Adicionais', 2),
 ('Omurice da Anya',        'Adicionais', 1),
 ('Gyudon do Denji',        'Adicionais', 1),
 ('Bento do Tanjiro',       'Ponto do ovo', 1),        ('Bento do Tanjiro',       'Adicionais', 2),
 ('Takoyaki U.A.',          'Molho extra', 1),
 ('Gyoza do Mikey',         'Molho extra', 1),
 ('Onigiri do Shikamaru',   'Molho extra', 1),
 ('Batatas do Sukuna',      'Nível de pimenta', 1),    ('Batatas do Sukuna',      'Molho extra', 2),
 ('Frango Imperial da Yor', 'Nível de pimenta', 1),    ('Frango Imperial da Yor', 'Molho extra', 2),
 ('Okonomiyaki U.A.',       'Molho extra', 1),
 ('Sukuna Red Velvet',      'Cobertura extra', 1),
 ('Parfait da Anya',        'Cobertura extra', 1),
 ('Chocolate do Sebastian', 'Cobertura extra', 1),
 ('Bat Berry Cake',         'Cobertura extra', 1),
 ('Taiyaki do Gojo',        'Cobertura extra', 1),
 ('Six Eyes',               'Gelo', 1),
 ('Anya Strawberry Milk',   'Gelo', 1),
 ('Cursed Energy',          'Gelo', 1),
 ('Nezuko Berry Soda',      'Gelo', 1),
 ('Midnight Soda',          'Gelo', 1),
 ('Blood Moon',             'Gelo', 1),
 ('Black Flame Pasta',      'Adicionais da massa', 1)
) AS v (prato, grupo, ordem)
JOIN prato p       ON p.nome = v.prato
JOIN grupo_opcao g ON g.nome = v.grupo;

-- ---------- Combos ----------
INSERT INTO combo (nome, descricao, tipo, desconto_percentual, ordem) VALUES
('Missão Rank S',      'Para quem volta de uma missão com fome de ninja: ramen, gyoza e uma soda gelada.',        'PRONTO',   10, 1),
('Domínio Expandido',  'Tudo o que há de mais intenso na casa, de uma vez: alho negro, pimenta e energia amaldiçoada.', 'PRONTO', 12, 2),
('Família Forger',     'Um jantar completo para dividir, com prato, petisco, sobremesa e o leite de morango.',    'PRONTO',   15, 3),
('Chá do Mordomo',     'A pausa da tarde: dois doces e um leite de morango para acompanhar.',                     'PRONTO',   10, 4),
('Noite de Lua Cheia', 'As criações da casa em tons escuros: massa, bolo e um mocktail vermelho.',                'PRONTO',   12, 5),
('Monte seu combo',    'Escolha um prato e uma bebida, complete com petisco e sobremesa se quiser, e ganhe desconto em tudo.', 'MONTAVEL', 10, 6);

INSERT INTO combo_etapa (combo_id, nome, obrigatoria, ordem)
SELECT c.id, v.nome, v.obrigatoria, v.ordem
FROM (VALUES
 ('Missão Rank S',      'Prato',     TRUE, 1), ('Missão Rank S',      'Petisco',        TRUE, 2), ('Missão Rank S',      'Bebida',    TRUE, 3),
 ('Domínio Expandido',  'Prato',     TRUE, 1), ('Domínio Expandido',  'Acompanhamento', TRUE, 2), ('Domínio Expandido',  'Bebida',    TRUE, 3),
 ('Família Forger',     'Prato',     TRUE, 1), ('Família Forger',     'Petisco',        TRUE, 2), ('Família Forger',     'Sobremesa', TRUE, 3),
 ('Família Forger',     'Bebida',    TRUE, 4),
 ('Chá do Mordomo',     'Primeiro doce', TRUE, 1), ('Chá do Mordomo', 'Segundo doce',   TRUE, 2), ('Chá do Mordomo',     'Bebida',    TRUE, 3),
 ('Noite de Lua Cheia', 'Prato',     TRUE, 1), ('Noite de Lua Cheia', 'Sobremesa',      TRUE, 2), ('Noite de Lua Cheia', 'Bebida',    TRUE, 3),
 ('Monte seu combo',    'Prato',     TRUE, 1), ('Monte seu combo',    'Bebida',         TRUE, 2),
 ('Monte seu combo',    'Petisco ou acompanhamento', FALSE, 3),       ('Monte seu combo',    'Sobremesa', FALSE, 4)
) AS v (combo, nome, obrigatoria, ordem)
JOIN combo c ON c.nome = v.combo;

-- Combos prontos: um prato fixo por etapa.
INSERT INTO combo_etapa_prato (combo_etapa_id, prato_id)
SELECT e.id, p.id
FROM (VALUES
 ('Missão Rank S',      'Prato',          'Ramen Ichiraku'),
 ('Missão Rank S',      'Petisco',        'Gyoza do Mikey'),
 ('Missão Rank S',      'Bebida',         'Six Eyes'),
 ('Domínio Expandido',  'Prato',          'Black Garlic Ramen'),
 ('Domínio Expandido',  'Acompanhamento', 'Batatas do Sukuna'),
 ('Domínio Expandido',  'Bebida',         'Cursed Energy'),
 ('Família Forger',     'Prato',          'Omurice da Anya'),
 ('Família Forger',     'Petisco',        'Frango Imperial da Yor'),
 ('Família Forger',     'Sobremesa',      'Parfait da Anya'),
 ('Família Forger',     'Bebida',         'Anya Strawberry Milk'),
 ('Chá do Mordomo',     'Primeiro doce',  'Chocolate do Sebastian'),
 ('Chá do Mordomo',     'Segundo doce',   'Taiyaki do Gojo'),
 ('Chá do Mordomo',     'Bebida',         'Anya Strawberry Milk'),
 ('Noite de Lua Cheia', 'Prato',          'Black Flame Pasta'),
 ('Noite de Lua Cheia', 'Sobremesa',      'Bat Berry Cake'),
 ('Noite de Lua Cheia', 'Bebida',         'Blood Moon')
) AS v (combo, etapa, prato)
JOIN combo c       ON c.nome = v.combo
JOIN combo_etapa e ON e.combo_id = c.id AND e.nome = v.etapa
JOIN prato p       ON p.nome = v.prato;

-- Monte seu combo: cada etapa aceita todos os pratos das categorias indicadas.
INSERT INTO combo_etapa_prato (combo_etapa_id, prato_id)
SELECT e.id, p.id
FROM (VALUES
 ('Prato',                     'Prato principal'),
 ('Prato',                     'Massa'),
 ('Prato',                     'Bento'),
 ('Bebida',                    'Bebida'),
 ('Bebida',                    'Bebida especial'),
 ('Petisco ou acompanhamento', 'Petisco'),
 ('Petisco ou acompanhamento', 'Acompanhamento'),
 ('Sobremesa',                 'Sobremesa')
) AS v (etapa, categoria)
JOIN combo c       ON c.nome = 'Monte seu combo'
JOIN combo_etapa e ON e.combo_id = c.id AND e.nome = v.etapa
JOIN categoria cat ON cat.nome = v.categoria
JOIN prato p       ON p.categoria_id = cat.id;
