-- =====================================================================
-- V6: prepara as tabelas de pedido para combos e complementos
-- =====================================================================

-- Cada linha do pedido guarda o preco do prato no momento da compra,
-- o desconto aplicado e, se veio de um combo, qual foi.
-- (preco_unitario, que ja existia, e o valor final de uma unidade:
--  preco_base com desconto + complementos.)
ALTER TABLE pedido_item ADD COLUMN preco_base          NUMERIC(10,2) NOT NULL DEFAULT 0;
ALTER TABLE pedido_item ADD COLUMN desconto_percentual NUMERIC(5,2)  NOT NULL DEFAULT 0;
ALTER TABLE pedido_item ADD COLUMN combo_id            BIGINT;
ALTER TABLE pedido_item ADD COLUMN combo_nome          VARCHAR(120);
ALTER TABLE pedido_item ADD COLUMN combo_chave         VARCHAR(40);
ALTER TABLE pedido_item ADD CONSTRAINT fk_pi_combo FOREIGN KEY (combo_id) REFERENCES combo (id);

-- Os complementos escolhidos em cada linha. Nome e preco sao copiados para ca:
-- se o cardapio mudar depois, o pedido antigo continua mostrando o que foi vendido.
CREATE TABLE pedido_item_opcao (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_item_id  BIGINT        NOT NULL,
    opcao_id        BIGINT        NOT NULL,
    nome            VARCHAR(100)  NOT NULL,
    preco_adicional NUMERIC(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_pio_pedido_item FOREIGN KEY (pedido_item_id) REFERENCES pedido_item (id),
    CONSTRAINT fk_pio_opcao       FOREIGN KEY (opcao_id)       REFERENCES opcao (id)
);

CREATE INDEX idx_pio_pedido_item ON pedido_item_opcao (pedido_item_id);
